from django.conf.urls.defaults import *

urlpatterns = patterns('ithink.views',
    url(r'^postadd/$', 'postadd', name='postadd'),
    url(r'^$', 'home_canvas', name="home"),
    url(r'^(?P<sort>votes|comments|latest|friends)/$', 'home_canvas', name='home_sorted_def'),
    url(r'^(?P<sort>votes|comments|latest|friends)/(?P<offset>\d+)/$', 'home_canvas', name='home_sorted'),
    url(r'^home_iframe/$', 'home_iframe', name='home_iframe'),
    url(r'^home_iframe/(?P<sort>votes|comments|latest|friends)/$', 'home_iframe', name='home_iframe_sorted_def'),
    url(r'^home_iframe/(?P<sort>votes|comments|latest|friends)/(?P<offset>\d+)/$', 'home_iframe', name='home_iframe_sorted'),
    
    url(r'^feature_iframe/$', 'feature_iframe', name='feature'),
    
    url(r'^tag/$', 'tag_view', name='tag_view_browse'),
    url(r'^tag/(?P<tag>[^/\s]+)/$', 'tag_view', name='tag_view'),
    url(r'^tag/(?P<tag>[^/\s]+)/(?P<sort>votes|comments|latest|friends)/$', 'tag_view', name='tag_view_sorted_def'),
    url(r'^tag/(?P<tag>[^/\s]+)/(?P<sort>votes|comments|latest|friends)/(?P<offset>\d+)/$', 'tag_view', name='tag_view_sorted'),
    url(r'^tag_iframe/(?P<tag>[^/\s]+)/$', 'tag_iframe', name='tag_iframe'),
    url(r'^tag_iframe/(?P<tag>[^/\s]+)/(?P<sort>votes|comments|latest|friends)/$', 'tag_iframe', name='tag_iframe_sorted_def'),
    url(r'^tag_iframe/(?P<tag>[^/\s]+)/(?P<sort>votes|comments|latest|friends)/(?P<offset>\d+)/$', 'tag_iframe', name='tag_iframe_sorted'),
    
    url(r'^my/$', 'my', name='my_def'),
    url(r'^my/(?P<stuff>thoughts|notes|followers|followings)/$', 'my', name='my_stuff_def'),
    url(r'^my/thoughts/(?P<cat>created|voted|commented|received)/$', 'my', name='my_thoughts_cat_def'),
    url(r'^my/thoughts/(?P<cat>created|voted|commented|received)/(?P<offset>\d+)/$', 'my', name='my_thoughts_cat_offset'),
    url(r'^my/(?P<stuff>notes|followers|followings)/$', 'my', name='my_stuff_def'),
    url(r'^my/(?P<stuff>thoughts|notes|followers|followings)/(?P<offset>\d+)/$', 'my', name='my_stuff_sorted'),
    
    url(r'^my_iframe/thoughts/(?P<cat>created|voted|commented|received)/$', 'my_iframe_thoughts', name='my_iframe_thoughts_def'),
    url(r'^my_iframe/thoughts/(?P<cat>created|voted|commented|received)/(?P<offset>\d+)/$', 'my_iframe_thoughts', name='my_iframe_thoughts_cat_sorted'),
    url(r'^my_iframe/(?P<stuff>notes|followers|followings)/$', 'my_iframe_stuff', name='my_iframe_stuff_def'),
    url(r'^my_iframe/(?P<stuff>notes|followers|followings)/(?P<offset>\d+)/$', 'my_iframe_stuff', name='my_iframe_stuff_sorted'),
    
    url(r'^profile/(?P<uid>\d+)/$', 'profile', name='profile_def'),
    url(r'^profile/(?P<uid>\d+)/(?P<stuff>thoughts|notes|followers|followings)/$', 'profile', name='profile_stuff_def'),
    url(r'^profile/(?P<uid>\d+)/thoughts/(?P<cat>created|voted|commented)/$', 'profile', name='profile_thoughts_cat_def'),
    url(r'^profile/(?P<uid>\d+)/thoughts/(?P<cat>created|voted|commented)/(?P<offset>\d+)/$', 'profile', name='profile_thoughts_cat_offset'),
    url(r'^profile/(?P<uid>\d+)/(?P<stuff>notes|followers|followings)/$', 'profile', name='profile_stuff_def'),
    url(r'^profile/(?P<uid>\d+)/(?P<stuff>notes|followers|followings)/(?P<offset>\d+)/$', 'profile', name='profile_stuff_offset'),
    
    url(r'^profile_iframe/(?P<uid>\d+)/thoughts/(?P<cat>created|voted|commented)/$', 'profile_iframe_thoughts', name='profile_iframe_thoughts_def'),
    url(r'^profile_iframe/(?P<uid>\d+)/thoughts/(?P<cat>created|voted|commented)/(?P<offset>\d+)/$', 'profile_iframe_thoughts', name='profile_iframe_thoughts_cat_offset'),
    url(r'^profile_iframe/(?P<uid>\d+)/(?P<stuff>notes|followers|followings)/$', 'profile_iframe_stuff', name='profile_iframe_stuff_def'),
    url(r'^profile_iframe/(?P<uid>\d+)/(?P<stuff>notes|followers|followings)/(?P<offset>\d+)/$', 'profile_iframe_stuff', name='profile_iframe_stuff_offset'),
    
    url(r'^people/$', 'people', name='people_def'),
    url(r'^people/(?P<cat>followers|thoughts|votes|comments|latest)/$', 'people', name='people_cat'),
    url(r'^people/(?P<cat>followers|thoughts|votes|comments|latest)/(?P<offset>\d+)/$', 'people', name='people_cat_offset'),
    
    url(r'^people_iframe/(?P<cat>followers|thoughts|votes|comments|latest)/$', 'people_iframe', name='people_iframe_def'),
    url(r'^people_iframe/(?P<cat>followers|thoughts|votes|comments|latest)/(?P<offset>\d+)/$', 'people_iframe', name='people_iframe_offset'),
    
    url(r'^new/$', 'new_canvas', name='new'),
    url(r'^new_iframe/$', 'new_iframe', name='new_iframe'),
    url(r'^create_thought/$', 'create_thought', name='create_thought'),
    url(r'^thoughts/(?P<thought_id>\d+)/$', 'thought_detail', name='thought_detail'),
    url(r'^thoughts/(?P<thought_id>\d+)/(?P<cat>comments|voters|followers)/$', 'thought_detail', name='thought_detail_cat'),
    url(r'^thought_iframe/(?P<thought_id>\d+)/(?P<cat>comments|voters|followers)/$', 'thought_iframe', name='thought_iframe'), 
    url(r'^vote/$', 'vote', name='vote'),
    url(r'^newcomment/$', 'new_comment', name='new_comment'),
    url(r'^nextcomments/$', 'next_comments', name='next_comments'),
    url(r'^prevcomments/$', 'prev_comments', name='prev_comments'),
    url(r'^nextvoters/$', 'next_voters', name='next_voters'),
    url(r'^prevvoters/$', 'prev_voters', name='prev_voters'),
    url(r'^newreply/$', 'new_reply', name='new_reply'),
    url(r'^getreplies/$', 'get_replies', name='get_replies'),
    url(r'^recommend/(?P<thought_id>\d+)/$', 'recommend', name='recommend'),
    url(r'^recommend_iframe/(?P<thought_id>\d+)/$', 'recommend_iframe', name='recommend_iframe'),
    url(r'^follow_user/(?P<to_uid>\d+)/(?P<from_uid>\d+)/$', 'follow_user', name='follow_user'),
    url(r'^invite/$', 'invite', name='invite'),
    url(r'^getsession/$', 'get_session_info', name='get_session'),
    url(r'^promote/$', 'promote', name='promote'),
#    url(r'^newnote/$', 'new_note', name='new_note'),
)